#!/usr/bin/env python3
"""
Wait for a locally-dropped file to sync to Nextcloud (via desktop client),
create a public share link with password + expiration, email the link to
the accountant.

Usage:
    python tools/nc_share_and_notify.py \\
        --file vystup/2026-04.7z \\
        --nc-path /Uctovnictvo/2026-04.7z \\
        --month 2026-04

Env required:
    NC_BASE_URL             e.g. https://cloud.example.com
    NC_USERNAME             Nextcloud username
    NC_APP_PASSWORD         Nextcloud app password
                            (Settings -> Security -> Generate app password)
    UCTOVNIK_EMAIL          accountant's email address

    SMTP_HOST               e.g. smtp.gmail.com
    SMTP_PORT               default 587 (STARTTLS)
    SMTP_USERNAME
    SMTP_PASSWORD

Two passwords are involved:
    1) share link password    — randomly generated by this script
    2) 7z archive password    — env ACC_ZIP_PASSWORD, NEVER printed/emailed

The share-link password is printed to STDOUT once at the end so you can
forward it to the accountant out-of-band (Signal/SMS/phone). It is not
sent in the email — that would defeat the point of a separate password.
"""
import argparse
import base64
import json
import os
import secrets
import smtplib
import ssl
import string
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta
from email.message import EmailMessage
from pathlib import Path


def basic_auth_header(user, pw):
    raw = f"{user}:{pw}".encode("utf-8")
    return "Basic " + base64.b64encode(raw).decode("ascii")


def webdav_url(base, user, remote_path):
    p = remote_path.lstrip("/")
    return (
        f"{base.rstrip('/')}/remote.php/dav/files/"
        f"{urllib.parse.quote(user)}/"
        f"{urllib.parse.quote(p, safe='/')}"
    )


def wait_for_sync(base, user, pw, remote_path, expected_size,
                  timeout=600, interval=10):
    """Poll HEAD on WebDAV until file appears with expected size."""
    url = webdav_url(base, user, remote_path)
    deadline = time.time() + timeout
    attempt = 0
    while time.time() < deadline:
        attempt += 1
        req = urllib.request.Request(
            url, method="HEAD",
            headers={"Authorization": basic_auth_header(user, pw)},
        )
        try:
            with urllib.request.urlopen(req, timeout=15) as r:
                length = int(r.headers.get("Content-Length", "0"))
                if length == expected_size:
                    print(f"  sync confirmed after {attempt} polls "
                          f"({length} bytes)", file=sys.stderr)
                    return True
                print(f"  poll {attempt}: file exists but size "
                      f"{length}/{expected_size} — still uploading",
                      file=sys.stderr)
        except urllib.error.HTTPError as e:
            if e.code == 404:
                print(f"  poll {attempt}: not yet visible", file=sys.stderr)
            elif e.code in (401, 403):
                print(f"ERROR: auth failed against Nextcloud ({e.code}). "
                      f"Check NC_USERNAME / NC_APP_PASSWORD.", file=sys.stderr)
                raise
            else:
                raise
        except urllib.error.URLError as e:
            print(f"  poll {attempt}: network error: {e}", file=sys.stderr)
        time.sleep(interval)
    return False


def create_public_share(base, user, pw, remote_path,
                         password, expire_days=30):
    """Call Nextcloud OCS Share API.

    Returns (share_url, expire_date_str). shareType=3 = public link.
    permissions=1 = read only (no upload, no edit).
    """
    url = (f"{base.rstrip('/')}/ocs/v2.php/apps/files_sharing/api/v1/shares"
           f"?format=json")
    expire = (datetime.now() + timedelta(days=expire_days)).strftime("%Y-%m-%d")
    body = urllib.parse.urlencode({
        "path": remote_path,
        "shareType": 3,
        "permissions": 1,
        "password": password,
        "expireDate": expire,
    }).encode("utf-8")
    req = urllib.request.Request(url, data=body, method="POST", headers={
        "Authorization": basic_auth_header(user, pw),
        "OCS-APIRequest": "true",
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json",
    })
    with urllib.request.urlopen(req, timeout=30) as r:
        resp = json.loads(r.read().decode("utf-8"))
    meta = resp.get("ocs", {}).get("meta", {})
    if meta.get("status") != "ok":
        raise RuntimeError(f"OCS share creation failed: {meta}")
    data = resp["ocs"]["data"]
    return data["url"], expire


def random_password(n=20):
    alphabet = string.ascii_letters + string.digits + "-_"
    return "".join(secrets.choice(alphabet) for _ in range(n))


def send_email(host, port, smtp_user, smtp_pw, to_addr, subject, body):
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = to_addr
    msg.set_content(body)
    ctx = ssl.create_default_context()
    if port == 465:
        with smtplib.SMTP_SSL(host, port, context=ctx) as s:
            s.login(smtp_user, smtp_pw)
            s.send_message(msg)
    else:
        with smtplib.SMTP(host, port) as s:
            s.starttls(context=ctx)
            s.login(smtp_user, smtp_pw)
            s.send_message(msg)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", required=True,
                    help="Local file path (already dropped in synced folder)")
    ap.add_argument("--nc-path", required=True,
                    help="Remote path on Nextcloud, e.g. /Uctovnictvo/2026-04.7z")
    ap.add_argument("--month", default="",
                    help="Mesiac pre subject emailu, napr. 2026-04")
    ap.add_argument("--expire-days", type=int, default=30)
    ap.add_argument("--sync-timeout", type=int, default=600,
                    help="seconds to wait for Nextcloud client sync")
    args = ap.parse_args()

    try:
        base = os.environ["NC_BASE_URL"]
        nc_user = os.environ["NC_USERNAME"]
        nc_pw = os.environ["NC_APP_PASSWORD"]
        uctovnik = os.environ["UCTOVNIK_EMAIL"]
        smtp_host = os.environ["SMTP_HOST"]
        smtp_user = os.environ["SMTP_USERNAME"]
        smtp_pw = os.environ["SMTP_PASSWORD"]
    except KeyError as e:
        print(f"ERROR: missing env var {e}", file=sys.stderr)
        return 2
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))

    f = Path(args.file)
    if not f.exists():
        print(f"ERROR: local file not found: {f}", file=sys.stderr)
        return 3
    expected_size = f.stat().st_size

    print(f"Waiting for Nextcloud sync of {args.nc_path} "
          f"({expected_size} bytes, timeout {args.sync_timeout}s)...",
          file=sys.stderr)
    if not wait_for_sync(base, nc_user, nc_pw, args.nc_path,
                          expected_size, timeout=args.sync_timeout):
        print(f"ERROR: file did not appear on Nextcloud within "
              f"{args.sync_timeout}s. Check that the desktop client is "
              f"running and the file is in a synced folder.",
              file=sys.stderr)
        return 4

    share_password = random_password()
    print("Creating public share link via OCS API...", file=sys.stderr)
    try:
        share_url, expire_date = create_public_share(
            base, nc_user, nc_pw, args.nc_path,
            share_password, args.expire_days,
        )
    except (urllib.error.HTTPError, urllib.error.URLError, RuntimeError) as e:
        print(f"ERROR: share creation failed: {e}", file=sys.stderr)
        return 5

    month_label = args.month or "aktualny mesiac"
    subject = f"Uctovne doklady za {month_label}"
    body = (
        f"Dobry den,\n\n"
        f"zasielam uctovne doklady za {month_label} ako sifrovany 7z archiv.\n\n"
        f"Stiahnutie:\n"
        f"  {share_url}\n\n"
        f"Heslo na zdielanie ako aj heslo na rozbalenie archivu Vam zaslem "
        f"samostatne (SMS / Signal).\n\n"
        f"Platnost zdielania: do {expire_date}.\n\n"
        f"S pozdravom\n"
    )
    try:
        send_email(smtp_host, smtp_port, smtp_user, smtp_pw,
                    uctovnik, subject, body)
    except (smtplib.SMTPException, OSError) as e:
        print(f"ERROR: SMTP send failed: {e}", file=sys.stderr)
        print(f"Share link was created: {share_url}", file=sys.stderr)
        return 6

    print(f"OK — share URL emailed to {uctovnik}", file=sys.stderr)
    print(f"OK — expires {expire_date}", file=sys.stderr)
    # The share password is the ONLY secret printed (to stdout, not stderr).
    # The orchestrator will pass this to the user, who delivers it
    # out-of-band to the accountant. ACC_ZIP_PASSWORD is never touched
    # by this script.
    print(f"SHARE_PASSWORD={share_password}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
